In [11]:
#Analytics and path imports
import os #good for working with files
import pathlib #find path
import re #all importable objects are compiled regular expressions
import pandas as pd #data analytics library

#Dash imports
import plotly.express as px #maps
import dash #the main library
import dash_table
import dash_core_components as dcc #dash components
import plotly.graph_objs as go
import dash_html_components as html #html dash components

VAplan = pd.read_csv('files/VAplan3.csv')
VAplan = VAplan[pd.notnull(VAplan['Risk'])]
VAplan

,County,Number of Students,Elementary school Plan,Secondary School Plan,Risk
0,Accomack,5171.0,2 days in-school (50% students) and 3 days vir...,2 days in-school (50% students) and 3 days vir...,Moderate
1,Albermarle,14435.0,All virtual,All virtual,Low
2,Alexandria,16307.0,All Virtual,All Virtual,Low
3,Alleghany,2024.0,2 days in-school (50% students) and 3 days vir...,2 days in-school (50% students) and 3 days vir...,Moderate
4,Amelia,1731.0,All students 4 days in-school and 1 day virtual,2 days in-school (50% students) and 3 days vir...,High
...,...,...,...,...,...
128,Willamsburg,11805.0,All virtual,All virtual,Low
129,Winchester,4392.0,2 days in-school (50% students) and 3 days vir...,2 days in-school (50% students) and 3 days vir...,High
130,Wise,5632.0,2 days in-school (50% students) and 3 days vir...,2 days in-school (50% students) and 3 days vir...,Moderate
131,Wythe,3982.0,All virtual,All virtual,Low
132,York,13184.0,All Virtual,All Virtual,Low

In [12]:
VAplan = pd.DataFrame(VAplan, columns =['County', 'Number of Students', 'Elementary School Plan', 'Secondary School Plan', 'Risk'])
#High Risk
#highRk = VAplan[ VAplan['Risk'] == "High"]
#highRk.to_csv('files/dsplit/Highrisk.csv')

#low Risk
#lowRk = VAplan[ VAplan['Risk'] == "Low"]
#lowRk.to_csv('files/dsplit/Lowrisk.csv')

#moderate Risk
#modRk = VAplan[ VAplan['Risk'] == "Moderate"]
#modRk.to_csv('files/dsplit/Modrisk.csv')

#still planning
#spRk = VAplan[ VAplan['Risk'] == "still planning"]
#spRk.to_csv('files/dsplit/sp.csv')

#only special needs are at risk as they come into school 
#osn = VAplan [ VAplan['Risk'] == "only special need in-person"]
#osn.to_csv('files/dsplit/osn.csv')
VAplan

,County,Number of Students,Elementary School Plan,Secondary School Plan,Risk
0,Accomack,5171.0,NaN,2 days in-school (50% students) and 3 days vir...,Moderate
1,Albermarle,14435.0,NaN,All virtual,Low
2,Alexandria,16307.0,NaN,All Virtual,Low
3,Alleghany,2024.0,NaN,2 days in-school (50% students) and 3 days vir...,Moderate
4,Amelia,1731.0,NaN,2 days in-school (50% students) and 3 days vir...,High
...,...,...,...,...,...
128,Willamsburg,11805.0,NaN,All virtual,Low
129,Winchester,4392.0,NaN,2 days in-school (50% students) and 3 days vir...,High
130,Wise,5632.0,NaN,2 days in-school (50% students) and 3 days vir...,Moderate
131,Wythe,3982.0,NaN,All virtual,Low
132,York,13184.0,NaN,All Virtual,Low